chore(deps): update dependency lint-staged to v15.4.3 (#601)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [lint-staged](https://redirect.github.com/lint-staged/lint-staged) |
[`15.3.0` ->
`15.4.3`](https://renovatebot.com/diffs/npm/lint-staged/15.3.0/15.4.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lint-staged/15.3.0/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lint-staged/15.3.0/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>lint-staged/lint-staged (lint-staged)</summary>

###
[`v15.4.3`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1543)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.2...v15.4.3)

##### Patch Changes

-
[#&#8203;1512](https://redirect.github.com/lint-staged/lint-staged/pull/1512)
[`cbfed1d`](https://redirect.github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1)
Thanks [@&#8203;tarik02](https://redirect.github.com/tarik02)! - Adjust
TypeScript types for the default export so that it can be used as a
value without error TS2693.

###
[`v15.4.2`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1542)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.1...v15.4.2)

##### Patch Changes

-
[#&#8203;1509](https://redirect.github.com/lint-staged/lint-staged/pull/1509)
[`8827ebf`](https://redirect.github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Change
*lint-staged*'s dependencies to use [caret (`^`)
ranges](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)
instead of [tilde
(`~`)](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1).
This makes it easier for package managers to perform dependency
management when minor-level updates are also permitted instead of just
patch-level.

###
[`v15.4.1`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1541)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.0...v15.4.1)

##### Patch Changes

-
[#&#8203;1504](https://redirect.github.com/lint-staged/lint-staged/pull/1504)
[`1c7a45e`](https://redirect.github.com/lint-staged/lint-staged/commit/1c7a45ed2c7fee9d5f55337be16a51e4c9b240e1)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Default
TypeScript config filenames match JS equivalents.

-
[#&#8203;1504](https://redirect.github.com/lint-staged/lint-staged/pull/1504)
[`9cc18c9`](https://redirect.github.com/lint-staged/lint-staged/commit/9cc18c9debb185490f9ae4f9c1d21ec8c2587393)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Add missing
conditional exports syntax for TypeScript types.

###
[`v15.4.0`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1540)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.3.0...v15.4.0)

##### Minor Changes

-
[#&#8203;1500](https://redirect.github.com/lint-staged/lint-staged/pull/1500)
[`a8ec1dd`](https://redirect.github.com/lint-staged/lint-staged/commit/a8ec1ddb587d2c1c2420dbb4baff8160f0ac46c9)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! -
*Lint-staged* now provides TypeScript types for the configuration and
main Node.js API. You can use the JSDoc syntax in your JS configuration
files:

    ```js
    /**
     * @&#8203;filename: lint-staged.config.js
     * @&#8203;type {import('lint-staged').Configuration}
     */
    export default {
      '*': 'prettier --write',
    }
    ```

It's also possible to use the `.ts` file extension for the configuration
if your Node.js version supports it. The `--experimental-strip-types`
flag was introduced in [Node.js
v22.6.0](https://redirect.github.com/nodejs/node/releases/tag/v22.6.0)
and unflagged in
[v23.6.0](https://redirect.github.com/nodejs/node/releases/tag/v23.6.0),
enabling Node.js to execute TypeScript files without additional
configuration.

    ```shell
    export NODE_OPTIONS="--experimental-strip-types"

    npx lint-staged --config lint-staged.config.ts
    ```

##### Patch Changes

-
[#&#8203;1501](https://redirect.github.com/lint-staged/lint-staged/pull/1501)
[`9b79364`](https://redirect.github.com/lint-staged/lint-staged/commit/9b793640e1f87b46e4f40fcfc1ecf9d6f6013ac9)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Handle
possible failures when logging user shell for debug info.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/r4ai/r4ai.dev).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMDcuMCIsInVwZGF0ZWRJblZlciI6IjM5LjEyNS4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: rai <96561881+r4ai@users.noreply.github.com>